###############################################################
# Copyright (c) 2023 Robert Bosch Manufacturing Solutions GmbH
# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################
test_name: Test APIs are protected with authentication

includes:
  - !include common.yaml
  - !include stage_auth.yaml

stages:
  - name: Test get search bpndiscovery without access token
    request:
      url: "{bpndiscovery_api_url:s}/api/v1.0/administration/connectors/bpnDiscovery/search"
      method: POST
      json:
        searchFilter:
          - type: "manufacturerPartId"
            keys:
              - "e2eTests-value"
    response:
      status_code: 401

  - type: ref
    id: request_auth_token

  - name: Authenticated request
    request:
      url: "{bpndiscovery_api_url:s}/api/v1.0/administration/connectors/bpnDiscovery/search"
      method: POST
      headers:
        Content-Type: application/json
        Authorization: "Bearer {access_token}"
      json:
        searchFilter:
          - type: "manufacturerPartId"
            keys:
              - "e2eTests-value"
    response:
      status_code: 200
      headers:
        content-type: application/json

---
test_name: Test create, search and delete bpn discovery endpoints

includes:
  - !include common.yaml
  - !include stage_auth.yaml

stages:
  - type: ref
    id: request_auth_token

  - name: Create Discovery endpoint
    request:
      url: "{bpndiscovery_api_url:s}/api/v1.0/administration/connectors/bpnDiscovery"
      method: POST
      headers:
        Content-Type: application/json
        Authorization: "Bearer {access_token}"
      json:
        type: "manufacturerPartId"
        key: "e2eTests-value"
    response:
      status_code: 201
      headers:
        content-type: application/json
      save:
        json:
          returned_resourceId: resourceId

  - name: Search bpn discovery
    request:
      url: "{bpndiscovery_api_url:s}/api/v1.0/administration/connectors/bpnDiscovery/search"
      method: POST
      headers:
        Content-Type: application/json
        Authorization: "Bearer {access_token}"
      json:
        searchFilter:
          - type: "manufacturerPartId"
            keys:
              - "e2eTests-value"
    response:
      status_code: 200
      headers:
        content-type: application/json

  - name: Delete bpn discovery endpoint
    request:
      url: "{bpndiscovery_api_url:s}/api/v1.0/administration/connectors/bpnDiscovery/{returned_resourceId:s}"
      method: DELETE
      headers:
        Content-Type: application/json
        Authorization: "Bearer {access_token}"
    response:
      status_code: 204